BasicApp/urls.py
from django.conf.urls import url
from BasicApp import views
app_name = 'BasicApp'

urlpatterns=[
    url(r'^register/',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

LearningUsers/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from BasicApp import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^BasicApp/',include('BasicApp.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special'),
]

BasicApp/models.py
# from django.db import models
# from django.contrib.auth.models import User
# # Create your models here.
#
# class UserProfileInfo(models.Model):
#
#     user = models.OneToOneField(User)
#
#
#     #additional
#     portfolio_site = models.URLField(blank=True)
#     profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
#
#     def __str__(self):
#         return self.user.username
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

BasicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from BasicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

BasicApp/views.py
from django.shortcuts import render
from BasicApp.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'BasicApp/index.html')

@login_required
def special(request):
    return HttpResponse("You're logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


# def register(request):
#
#     registered = False
#
#     if request.method == 'POST':
#
#         # Get info from "both" forms
#         # It appears as one form to the user on the .html page
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileInfoForm(data=request.POST)
#
#         # Check to see both forms are valid
#         if user_form.is_valid() and profile_form.is_valid():
#
#             # Save User Form to Database
#             user = user_form.save()
#
#             # Hash the password
#             user.set_password(user.password)
#
#             # Update with Hashed password
#             user.save()
#
#             # Now we deal with the extra info!
#
#             # Can't commit yet because we still need to manipulate
#             profile = profile_form.save(commit=False)
#
#             # Set One to One relationship between
#             # UserForm and UserProfileInfoForm
#             profile.user = user
#
#             # Check if they provided a profile picture
#             if 'profile_pic' in request.FILES:
#                 print('found it')
#                 # If yes, then grab it from the POST form reply
#                 profile.profile_pic = request.FILES['profile_pic']
#
#             # Now save model
#             profile.save()
#
#             # Registration Successful!
#             registered = True
#
#         else:
#             # One of the forms was invalid if this else gets called.
#             print(user_form.errors,profile_form.errors)
#
#     else:
#         # Was not an HTTP post so we just render the forms as blank.
#         user_form = UserForm()
#         profile_form = UserProfileInfoForm()
#
#     # This is the render and context dictionary to feed
#     # back to the registration.html file page.
#     return render(request,'BasicApp/registration.html',
#                           {'user_form':user_form,
#                            'profile_form':profile_form,
#                            'registered':registered})
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data= request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'BasicApp/registration.html',\
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


def user_login(request):
    if request.method =="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")

        else:
            print("Someone tried to login and fail")
            print("Username: {} \n password: {}".format(username,password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request,'BasicApp/login.html')

templates/BasicApp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Learning Users</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class ="navbar-brand" href="{% url 'index'%}">Django</a></li>
          <li><a class ="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class ="navbar-link" href="{% url 'BasicApp:register' %}">Signup</a></li>

          {% if user.is_authenticated %}
          <li><a class ="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class ="navbar-link" href="{% url 'BasicApp:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited -->
      {% endblock %}
    </div>
  </body>
</html>

templates/BasicApp/index.html
{% extends "BasicApp/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Django Level Five Homepage</h1>
</div>
{% endblock %}

templates/BasicApp/login.html
{% extends "BasicApp/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Login here!</h1>
  <form action="{% url 'BasicApp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter username">
      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" class="btn btn-primary" value="Login">
  </form>
</div>
{% endblock %}

templates/BasicApp/registration.html
{% extends "BasicApp/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
  <h1>Signup Page</h1>
  {% if registered %}
  <h1>Thank you for Signup!</h1>
  {% else %}
  <h1>Register here!</h1>
  <h3>Fill out the form</h3>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" class="btn btn-primary" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}